# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 28 May 2008 22:08:55 +0000
*               @ALL          0
*               @user         8
