<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: peter
 * Date: Wed, 02 Jul 2008 20:12:49 +0000
 */

$conf['title'] = 'AWKE Admin';
$conf['youarehere'] = 1;
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['registernotify'] = 'peter.knight@madcornishprojectionist.co.uk';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['notify'] = 'peter.knight@madcornishprojectionist.co.uk';
$conf['subscribers'] = 1;

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
